#!/usr/bin/env -S uv run --script
# -*- coding: utf-8 -*-
#
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "botocore",
#     "typer",
# ]
# ///

__author__ = "Victor COLOMB <victor@tarmactechnologies.com>"
__copyright__ = "Copyright (c) 2026 Tarmac Technologies"


import functools
import json
import sys
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Annotated

import botocore.model
import botocore.session
import botocore.signers
import typer


@dataclass
class Interrupt(Exception):
    status: int
    message: str


@functools.cache
def _get_aws_region_from_idms() -> str:
    response = urllib.request.urlopen(
        urllib.request.Request(
            "http://169.254.169.254/latest/api/token",
            method="PUT",
            headers={"X-aws-ec2-metadata-token-ttl-seconds": "5"},
        )
    )
    if response.status != 200:
        raise Interrupt(2, "Could not retrieve IDMS token.")
    token = response.text

    response = urllib.request.urlopen(
        urllib.request.Request(
            "http://169.254.169.254/latest/dynamic/instance-identity/document",
            method="GET",
            headers={"X-aws-ec2-metadata-token": token},
        )
    )
    if response.status != 200:
        raise Interrupt(2, "Could not retrieve region from IDMS.")
    region = json.loads(response.text).get("region")

    assert isinstance(region, str)
    return region


def get_aws_region(session: botocore.session.Session) -> str:
    if (region := session.get_config_variable("region")) is not None:
        assert isinstance(region, str)
        return region

    return _get_aws_region_from_idms()


def _generate_iam_token(cluster_name: str, username: str, lifetime: int) -> str:
    session = botocore.session.get_session()
    region = get_aws_region(session)
    credentials = session.get_credentials()
    assert credentials is not None

    signer = botocore.signers.RequestSigner(
        service_id=botocore.model.ServiceId("elasticache"),
        region_name=region,
        signing_name="elasticache",
        signature_version="v4",
        credentials=credentials,
        event_emitter=session.get_component("event_emitter"),
    )
    url = urllib.parse.urlunparse(
        urllib.parse.ParseResult(
            scheme="https",
            netloc=cluster_name,
            path="/",
            query=urllib.parse.urlencode({"Action": "connect", "User": username}),
            params="",
            fragment="",
        )
    )

    signed_url = signer.generate_presigned_url(
        request_dict={
            "method": "GET",
            "url": url,
            "body": {},
            "headers": {},
            "context": {},
        },
        operation_name="connect",
        expires_in=lifetime * 60,
        region_name=region,
    )
    return signed_url.removeprefix("https://")


def main(
    cluster_name: Annotated[
        str, typer.Argument(help="Name of the Valkey ElastiCache cluster")
    ],
    username: Annotated[str, typer.Argument(help="Valkey username")],
    lifetime: Annotated[
        int,
        typer.Option(
            help=(
                "Duration of the password validity, in minutes. "
                "Should not exceed the current AWS session duration."
            )
        ),
    ] = 15,
) -> None:
    """
    Generate a temporary Valkey ElastiCache password using IAM.
    """
    try:
        token = _generate_iam_token(cluster_name, username, lifetime)
    except Interrupt as exc:
        print(exc.message, file=sys.stderr)
        raise typer.Exit(exc.status)

    print(token)


if __name__ == "__main__":
    typer.run(main)
