#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Author: Victor Colomb <victor@tarmactechnologies.com>
# Copyright (c) 2026 Tarmac Technologies

## Usage: pg-update-table [options]
##
## Required options:
##  -d|--database [name]: Name of the database to update
##  -t|--table [table_name]: Name of the table to update
##  -u|--username [username]: Username for the PostgreSQL server
##  -c|--column [column_name]: Name of the column to update
##  -v|--value [value]: Value to update the column with
##
## Optional options:
##  --help: Display this help message and exit.
##  -h|--host [host]: Hostname or IP address of the PostgreSQL server [default: 127.0.0.1]
##  -p|--port [port]: Port number of the PostgreSQL server [default: 5432]
##  -b|--batch-size [size]: Batch size for deletion [default: 1000]
##  -k|--primary-key [column_name]: Name of the primary key column [default: id]
##  -m|--min [value]: Minimum value for the primary key
##  -M|--max [value]: Maximum value for the primary key
##  -P|--password [password]: Password for the PostgreSQL server. If not provided, the script will prompt for it.

set -euo pipefail
IFS=$'\n\t'

usage() {
	[ "$*" ] && echo "$0: $*"
	sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
} 2>/dev/null


# === Parameters ===

BATCH_SIZE=1000
HOST=127.0.0.1
PORT=5432
PRIMARY_KEY=id
MIN_ID=""
MAX_ID=""

set +u
while [[ "$1" =~ ^- ]]; do case $1 in
	--help)
		echo "Update values in a PostgreSQL table in batches."
		usage
		exit 0
		;;
	-d | --database)
		shift
		DB_NAME=$1
		;;
	-t | --table)
		shift
		TABLE=$1
		;;
	-u | --username)
		shift
		USERNAME=$1
		;;
	-c | --column)
		shift
		COLUMN=$1
		;;
	-v | --value)
		shift
		VALUE=$1
		;;
	-h | --host)
		shift
		HOST=$1
		;;
	-p | --port)
		shift
		PORT=$1
		;;
	-b | --batch-size)
		shift
		BATCH_SIZE=$1
		;;
	-k | --primary-key)
		shift
		PRIMARY_KEY=$1
		;;
	-m | --min)
		shift
		MIN_ID=$1
		;;
	-M | --max)
		shift
		MAX_ID=$1
		;;
	-P | --password)
		shift
		PASSWORD=$1
		;;
	*)
		echo "Unknown option: $1"
		usage
		exit 1
		;;
esac; shift; done

[[ -z "$DB_NAME" ]] && echo "[!] -d or --database name is required" >&2 && usage && exit 1
[[ -z "$TABLE" ]] && echo "[!] -t or --table name is required" >&2 && usage && exit 1
[[ -z "$USERNAME" ]] && echo "[!] -u or --username is required" >&2 && usage && exit 1
[[ -z "$COLUMN" ]] && echo "[!] -c or --column name is required" >&2 && usage && exit 1
[[ -z "$VALUE" ]] && echo "[!] -v or --value is required" >&2 && usage && exit 1

[[ -z "$PASSWORD" ]] && read -s -p "Enter password for $USERNAME@$HOST:$PORT/$DB_NAME: " PASSWORD && echo
export PGPASSWORD=$PASSWORD

set -u


# === Get min and max id ===

[[ -z "$MIN_ID" ]] && MIN_ID=$(psql -h "$HOST" -p "$PORT" -d "$DB_NAME" -U "$USERNAME" -tAc "SELECT MIN($PRIMARY_KEY) FROM $TABLE")
[[ -z "$MAX_ID" ]] && MAX_ID=$(psql -h "$HOST" -p "$PORT" -d "$DB_NAME" -U "$USERNAME" -tAc "SELECT MAX($PRIMARY_KEY) FROM $TABLE")
echo "Min ID: $MIN_ID // Max ID: $MAX_ID"

CURRENT_ID=$MIN_ID


# === Delete in batches ===

if [[ "${VALUE^^}" == "NULL" ]]; then
	SET="= NULL"
	CONDITIONAL="IS NOT NULL"
else
	SET="= '$VALUE'"
	CONDITIONAL="= '$VALUE'"
fi

while [ "$CURRENT_ID" -le "$MAX_ID" ]; do
	upper=$((CURRENT_ID + BATCH_SIZE - 1))
	[[ $upper -gt $MAX_ID ]] && upper=$MAX_ID

	psql -h "$HOST" -p "$PORT" -d "$DB_NAME" -U "$USERNAME" -c "
		UPDATE $TABLE
		SET $COLUMN $SET
		WHERE $PRIMARY_KEY >= $CURRENT_ID
			AND $PRIMARY_KEY <= $upper
			AND $COLUMN $CONDITIONAL;
	"

	echo "Updated IDs from $CURRENT_ID to $upper"

	CURRENT_ID=$((CURRENT_ID + BATCH_SIZE))
done
